const responses = {
    "hello": ["Hi , How are you?","Hello, How are you doing?","Hey how can I help you?"],
    "how are you?": ["I am fine, How are you?","I am good, How are you doing?"],
    "i am fine": ["Good to hear that","Nice to hear that"],
    "i am good": ["Good to hear that","Nice to hear that"],
    "what is your name?": ["My name is ChatBot","I am ChatBot"],
    "what's your name?": ["My name is ChatBot","I am ChatBot"],
    "what is your age?": ["As a computer program, I am ageless.","I am ageless."],
    "what's your age?": ["As a computer program, I am ageless.","I am ageless. by the way, how old are you?"],
    "what are you doing?": ["I am chatting with you","I am talking to you"],
    "what's up?": ["Nothing much","I am chatting with you"],
    "what do you do?": ["I am chatting with you","I am talking to you"],
    "what do you like?": ["I like to help people","I like to chat with people","I like to talk to people"],
    "what do you like to do?": ["I like to help people","I like to chat with people","I like to talk to people"],
    "how old are you?": ["As a computer program, I am ageless.","I am ageless. by the way, how old are you?"],
    "how are you doing?": ["I am fine, How are you?","I am good, How are you doing?"],
    "how are you": ["I am fine, How are you?","I am good, How are you doing?"],
    "who is your creator?": ["My creator is vivek thakur","vivek thakur is my creator"],
    "who created you?": ["My creator is vivek thakur","vivek thakur is my creator"],
    "who is your father?": ["My creator is vivek thakur","vivek thakur is my creator"],
    "do you have a father?": ["My creator is vivek thakur","vivek thakur is my creator"],
    "why did you come here?": ["I came here to chat with you","I came here to talk to you"],
    "why did he created you?": ["He created me to chat with you","He created me to talk to you"],
    "i am bored": ["I am here to chat with you","I am here to talk to you"],
    "not good at all": ["I am here to chat with you","I am here to talk to you"],
    "bro":["Hey bro","Hey bro, how are you doing?"],
    "brother":["Hey bro","Hey bro, how are you doing?"],
    "sister":["Hey sis","Hey sis, how are you doing?"],
    "sis":["Hey sis","Hey sis, how are you doing?"],
    "i am sad":["Hey don't be sad","Hey don't be sad, everything will be fine"],
    "i am happy":["Hey that's great","Hey that's great, I am happy for you"],
    "i am angry":["Hey don't be angry","Hey don't be angry, everything will be fine"],
    "i am excited":["Hey that's great","Hey that's great, I am happy for you"],
    "i am depressed":["Hey don't be depressed","Hey don't be depressed, everything will be fine"],
    "i am feeling depressed":["Hey don't be depressed","Hey don't be depressed, everything will be fine"],
    "ram ram":["Ram ram","Ram ram, how are you doing?"],
    "namaste":["Namaste","Namaste, how are you doing?"],
    "hey":["Hey","Hey, how are you doing?"],
    "hi":["Hi","Hi, how are you doing?"],
    "hello":["Hello","Hello, how are you doing?"],
    "howdy":["Howdy","Howdy, how are you doing?"],
    "hola":["Hola","Hola, how are you doing?"],
    "bonjour":["Bonjour","Bonjour, how are you doing?"],
    "hallo":["Hallo","Hallo, how are you doing?"],
    "can you help me?":["Yes, I can help you","Yes, I can help you, how can I help you?"],
    "goog morning":["Good morning","Good morning, how are you doing?"],
    "good afternoon":["Good afternoon","Good afternoon, how are you doing?"],
    "good evening":["Good evening","Good evening, how are you doing?"],
    "good night":["Good night","Good night, how are you doing?"],
    "thanks":["You are welcome","You are welcome, how can I help you?"],
    "thank you":["You are welcome","You are welcome, how can I help you?"],
    "bye":["Bye","Bye, see you later"]
};

export default responses;